services:
  - type: web
    name: lynqit-chat-app
    env: node
    buildCommand: echo "Environment check:" && echo "VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID" && echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" && npm run render-build
    startCommand: npm run render-start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: RENDER
        value: true
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      # Email configuration - set these in the Render dashboard
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      # Cloudinary configuration - set these in the Render dashboard
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: PRODUCTION_URL
        value: https://lynqit.onrender.com
      - key: LOCAL_URL
        value: http://localhost:5173
      # Google OAuth configuration - Frontend needs VITE_ prefix
      - key: VITE_GOOGLE_CLIENT_ID
        value: 461128965954-90fcltci30rissdg8825l3lv5e0ifpfd.apps.googleusercontent.com
      # Backend Google OAuth configuration
      - key: GOOGLE_CLIENT_ID
        value: 461128965954-90fcltci30rissdg8825l3lv5e0ifpfd.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      # Additional environment variables for debugging
      - key: VITE_NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://lynqit.onrender.com/api
    autoDeploy: true